### ISSUE TITLE
Files API Service Turndown, starting on July 28th!

### ISSUE THREAD

**Issue by Philoozushi** [django-nonrel/djangoappengine#105]
Google will shut down the Files API as announced there :
https://cloud.google.com/appengine/docs/deprecations/files_api

Decommission Date | Decommission Event
------------ | -------------
May 20, 2015 | No new applications will have access to the Files API. Applications created prior to May 20, 2015 will continue to run without any issues. However, we strongly encourage developers to start switching over to the Cloud Storage Client Library today.
July 28th, 2015 | Starting at 12pm Pacific Time, the Files API will be temporarily shutdown for 24 hrs.
**August 4th, 2015** | **We will permanently shut down the Files API at 12:00pm Pacific time.**

- Migrations strategies will depend on the use cases
- Google recommends using the Google Cloud Storage and its client library
- but...

**Djangoappengine's file storage will be affected and won't work anymore!**
https://github.com/django-nonrel/djangoappengine/blob/master/djangoappengine/storage.py

**Comment by aburgel** [comment]
Take a look at #78
